// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDonvlTobGZpOhUsxC-mzY4IZe_GGouuwE',
    appId: '1:591509844503:web:739430b021b2b7ae26e252',
    messagingSenderId: '591509844503',
    projectId: 'app-autismo-25f44',
    authDomain: 'app-autismo-25f44.firebaseapp.com',
    storageBucket: 'app-autismo-25f44.firebasestorage.app',
    measurementId: 'G-XDZZ5Z7L9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9_EcZ9rxiHtRCypdQADCarxm6A9XYYE',
    appId: '1:591509844503:android:cb109334431d2ca726e252',
    messagingSenderId: '591509844503',
    projectId: 'app-autismo-25f44',
    storageBucket: 'app-autismo-25f44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHuKNT-l3iPYAxstjGWNZ9mr3Ikv47h2E',
    appId: '1:591509844503:ios:69798e0e1ee93bf326e252',
    messagingSenderId: '591509844503',
    projectId: 'app-autismo-25f44',
    storageBucket: 'app-autismo-25f44.firebasestorage.app',
    iosBundleId: 'com.example.appAutismoUabc',
  );
}
